import type { Metadata } from "next"

import { FONT_VARIABLE_CLASS } from "@/lib/font"
import "@/styles/globals.scss"
import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import "@mantine/core/styles.css"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={FONT_VARIABLE_CLASS}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  )
}
